language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
after_success: |
  if [ -n "$github_token" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # This generates a `web` directory containing the website.
    make web
    cd web
    git init
    git checkout -b gh-pages
    git add .
    git -c user.name='nir099' -c user.email='a.m.s.nirmal.a@gmail.com' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://nir099:$github_token@github.com/nir099/zy-cy.git -gh-pages gh-pages &>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi